### ISSUE TITLE
使用 docker-compose 部署访问报错。

### ISSUE THREAD

**Issue by ruicky** [hamster1963/nezha-dash#27]
# 基本信息

+ 镜像：https://hub.docker.com/layers/hamster1963/nezha-dash/latest/images/sha256-da17cf6c882b31c7128b988a273fbe173e7bac64a1805e1cedb722d017376ba8?context=explore 
+ 部署方式：docker-compose
+ 访问方式：https://xx.com（域名访问）
+ 错误信息：
```code
Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.
    at ek (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:139520)
    at eP (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:141995)
    at eE (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135346)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  digest: '4220909560'
```
希望帮忙定位一下这里的报错是如何产生的，我该如何使得这个程序正常访问，🙏

**Comment by hamster1963** [comment]
.env 配置文件是否已经配置好，哪吒面板信息与token是否填写好，且放置在docker-compose.yml同等目录下呢？

**Comment by ruicky** [comment]
已定位到原因，是因为NezhaBaseUrl=http://0.0.0.0:8008 这里的配置， 原以为只要本地访问成功就可以，但是好像不是这样，配置成域名，正常访问了。

**Comment by hamster1963** [comment]
感谢你提出的问题，我会优化错误提示。
